language: c
before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install software-properties-common
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa
  - sudo apt-get update
  - sudo apt-get install -y gcc make criterion-dev gcovr
script: make && make test
