language: c
before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install software-properties-common
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa
  - sudo apt-get update
  - sudo apt-get install -y gcc-4.9 make criterion-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60
  - sudo -H pip install gcovr
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
  - tar xf lcov_1.13.orig.tar.gz
  - sudo make -C lcov-1.13/ install
  - gem install coveralls-lcov
  - sudo ln -sf /usr/bin/gcov-4.9 /usr/bin/gcov
script: make && make test
after_success:
  - lcov --directory _objs/src --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
